[package]
name = "ui_toolkit"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_tweening = { version = "0.11.0", features = ["default", "bevy_ui"] }
rand = "0.8.5"
sickle_ui = "0.3.0"